### PR TITLE
Protected

### PR DESCRIPTION
**Pull request by bmoniey**
This is a request to change private data to protected data in the Adafruit_SSD1306 class. This will simplify class derivation and encourage experimentation.

### CODE REVIEW

**Comment by ladyada** [comment]
hi this required doxygen updates since now the functions are exposed

**Comment by BillyDonahue** [comment]
I know the API stability for these Arduino libs has been a priority at least in the GFX base class. The downside of this PR is that `protected` is basically `public` in terms of API exposure. So if Adafruit later refactors parts of the SSD1306 internals it would be a breaking change for user code that used those protected members. It would be cool if clients had to "opt-in" to use the private details and acknowledge the risk of their app breaking as the library evolves.

An alternative to full protected access for everything would be to have `SSD1306` declare a `friend class` (called `SSD1306Internals` or something) which would then have private access. A nested class would also work I guess. We wouldn't have to actually define that class, but if client code did provide a definition, that class would have access to the SSD1306 internals. It could be an explicit hook mechanism and it would be clear that any client code relying on that they're depending on details that are subject to change.

**Comment by BillyDonahue** [comment]
> Adding a friend class is more memory and flash, even if just a little bit.

I don't believe this to be the case. Maybe worth measuring. You're making an argument based on a very keen sense of space efficiency which I appreciate. But if anything, I'd expect the `protected` access scheme to be less space-efficient than the `friend class` scheme. `SSD1306` has `Adafruit_GFX` as a base class, so it's polymorphic. To get access to the protected members of `SSD1306` an app would have to introduce another class that's derived from SSD1306. That derived class would therefore introduce a new vtable. The friend class would not incur that cost.

If somebody is willing to pin their SSD1306 library to a specific version they could just locally modify it. If they're that tight for space they would have to locally modify it to take out the appx 3kB of splash bitmaps and other stuff they might not need.

**Comment by bmoniey** [comment]
Hello Dylan,

I've done quite a bit with doxygen. I can add the proper tags according to
the already documented public interface style and level of detail.

Thanks - a task for this weekend!

Cheers,

Brian

**Comment by dherrada** [comment]
@bmoniey awesome. Thanks for taking that on!

**Comment by ladyada** [comment]
very close! please run clang-format :)
https://learn.adafruit.com/the-well-automated-arduino-library/formatting-with-clang-format

**Review by bmoniey — COMMENTED** [review]
Ran clang-format on AdafruitSSD1306.cpp,.h using llvm build for windows. Pretty. Thanks!

**Comment by ladyada** [comment]
hmm check the output of CI, its not passing clang-format
https://github.com/adafruit/Adafruit_SSD1306/runs/3847721168

**Review by bmoniey — COMMENTED** [review]
My new friend Travis got a taste of windows and didn't like it. I was able to reproduce the issue using the run-clang-format.py script on a pi.  I ran the header through clang-format-5.0 from the pi and it cleaned things up. Looked like some sort of difference in the tab indentations on the inline doxygen comments.

**Review by ladyada — APPROVED** [review]
amazing!

**Pull request merged**
