### PR TITLE
examples: x64_spi: fix compile error in newer compilers

### PR DESCRIPTION
**Pull request by karlp**
Without prototypes, setup/loop need to be after the test methods.  This is a
minimal change to compile with arduino 1.6.5

Signed-off-by: Karl Palsson karlp@tweak.net.au

Change is simply a bulk move of setup/loop down to the end of the file.

### CODE REVIEW

**Comment by fingolfin** [comment]
Hmm, it compiles just fine for me with Arduino 1.6.7, even without this change?!

**Comment by karlp** [comment]
Probably related to https://github.com/esp8266/Arduino/issues/1066

Changing the order means you don't need to worry about the tools.

**Comment by fingolfin** [comment]
Good C code of course should always have prototypes... but given the nature of these examples, moving setup() as you do indeed seems to be the quickest solution to this long-term problem.

**Comment by PaintYourDragon** [comment]
Appreciate the pull request. Works OK in current Arduino IDE, going to close this.

Pedantically speaking, yes, there should be prototypes or setup & loop should be moved to the bottom. However, as these are "level 1" examples and may be reworked by novice users, explaining top-down how the code works is a whole lot simpler with setup & loop close to the top and no prototypes.

i.e. from a Good and Proper C Perspective(tm), Arduino is doing this Wrong...but in this situation, I'm okay with wrong.

**Comment by karlp** [comment]
Yes, wait long enough and things become obsolete or fixed by other people :)

This was "fixed" by https://github.com/arduino/arduino-builder/issues/68 upstream.

**Pull request closed without merging**
